name: flutter_store_review
description: Wrap AppStore Review API for Flutter
version: 0.0.3
author: Ken <ken.shao@gmail.com>
homepage: https://github.com/pedia/flutter_store_review

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  platform: ^2.2.0

flutter:
  plugin:
    androidPackage: pedia.storereview.flutterstorereview
    pluginClass: FlutterStoreReviewPlugin
