name: flutter_store_review
description: Wrap AppStore Review API for Flutter
version: 0.0.1
author: Ken <ken.shao@gmail.com>
homepage: https://github.com/pedia/flutter_store_review

dependencies:
  flutter:
    sdk: flutter

  platform:

flutter:
  plugin:
    androidPackage: pedia.storereview.flutterstorereview
    pluginClass: FlutterStoreReviewPlugin
